import Default from "@/app/layouts/default/default";

export const metadata = {
	title: "Khalif | Web Log",
	description: "Generated by create next app",
};
const HomePage = () => {
	return (
		<Default>
			<h1>Allah Mohan</h1>
		</Default>
	);
};
export default HomePage;
