"use client";
import Default from "@/app/layouts/default/default";
import "./style.scss";
import { GetData } from "@/app/utils/api/getData";
import Link from "next/link";
import Image from "next/image";
import RectangleSkeleton from "@/app/components/common/skeleton/skeleton";
// export const metadata = {
// 	title: "Khalif | Web Log",
// 	description: "Generated by create next app",
// };
const HomePage = () => {
	const { data, isLoading, isError, error } = GetData(
		"users",
		process.env.NEXT_PUBLIC_API_URL + "users"
	);
	console.log(data);
	return (
		<Default>
			<section id="homePage" className="Container">
				<h1 className="text-white text-5xl font-bold font-slab pb-[45px] inline-flex">
					Meet Our Users (
					{isLoading ? (
						<RectangleSkeleton width="30px" height="30px" />
					) : (
						data?.result?.success?.length
					)}
					)
				</h1>
				<div className="usersList">
					<div className="grid grid-cols-12 gap-6">
						{data?.result?.success?.map((item: any, index: string) => {
							return (
								<div className="col-span-2" key={index}>
									<Link
										href={item._id}
										className="flex items-center flex-col bg-[#323443] rounded-lg justify-center gap-y-4 p-[25px]"
									>
										<Image
											className="rounded-full"
											src="/khalif.jpeg"
											width={150}
											height={150}
											alt="Picture of the author"
										/>
										<div className="flex flex-col items-center">
											<h1 className="text-white text-lg font-poppins">
												{item.name}
											</h1>
											<p className="text-[#C9C9C9] text-sm ">{item.email}</p>
										</div>
									</Link>
								</div>
							);
						})}
					</div>
				</div>
			</section>
		</Default>
	);
};
export default HomePage;
