"use client";
import Link from "next/link";
import Image from "next/image";
import { GetData } from "../../utils/api/getData";
import Default from "../../layouts/default/default";
import RectangleSkeleton from "../../components/common/skeleton/skeleton";

// export const metadata = {
// 	title: "Khalif | Web Log",
// 	description: "Generated by create next app",
// };

const HomePage = () => {
	const { data, isLoading } = GetData(
		"users",
		process.env.NEXT_PUBLIC_API_URL + "users"
	);

	console.log(data);
	return (
		<Default>
			<section id="homePage" className="Container">
				<h1 className="text-white text-5xl font-bold font-slab pb-[45px] inline-flex">
					Meet Our Users (
					{isLoading ? (
						<RectangleSkeleton width="30px" height="30px" />
					) : (
						data?.result?.success?.length
					)}
					)
				</h1>
				<div className="usersList">
					<div className="grid grid-cols-12 gap-6">
						{isLoading ? (
							<RectangleSkeleton width="30px" height="30px" />
						) : Array.isArray(data?.result?.success) ? (
							data.result.success.map((item, index) => {
								return (
									<div
										className="col-span-12 md:col-span-6 lg:col-span-4 xl:col-span-4 2xl:col-span-3 "
										key={index}
									>
										<div className="py-8 px-8 max-w-sm mx-auto bg-white rounded-xl shadow-lg space-y-2 sm:py-4 sm:flex sm:items-center sm:space-y-0 sm:space-x-6">
											<Image
												className="block mx-auto h-24 rounded-full sm:mx-0 sm:shrink-0"
												src={
													item?.profilePicture
														? item?.profilePicture
														: item?.gender === "male"
														? "/male.svg"
														: "/female.svg"
												}
												alt="Woman's Face"
												width={100}
												height={100}
											/>
											<div className="text-center space-y-2 sm:text-left">
												<div className="space-y-0.5">
													<p className="text-lg text-black font-semibold">
														{item.name}
													</p>
													<p className="text-slate-500 font-medium">
														{item.email}
													</p>
												</div>
												<Link
													href={`/user/${item._id}`}
													className="px-4 py-1 text-sm text-purple-600 font-semibold rounded-full border border-purple-200 hover:text-white hover:bg-purple-600 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-offset-2"
												>
													View Profile
												</Link>
											</div>
										</div>
									</div>
								);
							})
						) : (
							<span></span>
						)}
					</div>
				</div>
			</section>
		</Default>
	);
};
export default HomePage;
