"use client";
import Default from "@/app/layouts/default/default";
import { GetData } from "@/app/utils/api/getData";
import Image from "next/image";

// export const metadata = {
// 	title: "Khalif | Web Log",
// 	description: "Generated by create next app",
// };
const UserDetailsPage = ({ params }: any) => {
	const { data, isLoading, isError, error } = GetData(
		"users",
		process.env.NEXT_PUBLIC_API_URL + "single-user/" + params.id
	);
	console.log(data);
	return (
		<Default>
			<div className="Container">
				{/* <div
					className="addbg"
					style={{
						backgroundImage:
							'url("https://images.unsplash.com/photo-1499336315816-097655dcfbda?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2710&q=80")',
						backgroundSize: "cover",
						backgroundPosition: "center",
						height: "350px",
						width: "100%",
					}}
				>
					
				</div> */}
				<div className="mainContent mx-auto  max-w-6xl  bg-white p-4 md:p-16 rounded-lg ">
					<div className="top">
						<div className="grid grid-cols-12 items-center">
							<div className="col-span-4">
								<p>{data?.result?.success?.phone}</p>
								<p>{data?.result?.success?.email}</p>
							</div>
							<div className="col-span-4 flex justify-center">
								<Image
									className="block mx-auto h-24 rounded-full sm:mx-0 sm:shrink-0"
									src={
										data?.result?.success?.profilePicture
											? data?.result?.success?.profilePicture
											: data?.result?.success?.gender === "male"
											? "/male.svg"
											: "/female.svg"
									}
									alt="Woman's Face"
									width={100}
									height={100}
								/>
							</div>
							<div className="col-span-4 flex justify-end">
								<button>Edit</button>
								<button>Delete</button>
							</div>
						</div>
					</div>
					<div className="center border-b border-[#4d4d4d] py-[35px] mb-[35px] text-center">
						<h1>{data?.result?.success?.name}</h1>
						<p>{data?.result?.success?.gender}</p>
						<p>{data?.result?.success?.dateOfBirth}</p>
						<p>{data?.result?.success?.address}</p>
					</div>
					<div className="bottom text-center">
						{data?.result?.success?.biography}
					</div>
				</div>
			</div>
		</Default>
	);
};
export default UserDetailsPage;
